
default: &default
  adapter: <%= ENV.fetch("DB_ADAPTER", "sqlite3") %>
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "rails_min_users") %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

  ssl_mode: VERIFY_IDENTITY
  sslca: /etc/ssl/certs/azure-mysql-roots.pem
  
