name: Deploy Rails App to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.VM_PUBLIC_IP }} << 'EOF'
          cd ~/rails-demo
          git fetch --all
          git reset --hard origin/main
          bundle install --without development test
          RAILS_ENV=production rails db:migrate
          sudo systemctl restart railsapp
          EOF
