name: Deploy Rails App to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, azure, vm]
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd /home/gha/rails-minimal-users
          git fetch --all
          git reset --hard origin/main
          bundle install --jobs 4
          RAILS_ENV=production rails db:migrate
          sudo systemctl restart railsapp
          echo "Deployment to Azure VM completed."
          